image: gitpod/workspace-python

tasks:
  - name: Install Dependencies
    init: |
      cd /workspace/incident-commander-ai-demo
      pip install -r app/requirements.txt
      echo "✅ Dependencies installed"
    
  - name: Run API Server
    command: |
      cd /workspace/incident-commander-ai-demo/app
      echo "🚀 Starting Checkout API on port 8000..."
      uvicorn main:app --host 0.0.0.0 --port 8000 --reload
    
  - name: Monitor Logs
    command: |
      cd /workspace/incident-commander-ai-demo
      echo "📋 Waiting for logs to be generated..."
      sleep 5
      echo "📋 Tailing application logs (logs/app.log)..."
      tail -f logs/app.log 2>/dev/null || echo "No logs yet. Run the incident simulation to generate logs."

ports:
  - port: 8000
    onOpen: notify
    visibility: public
    description: Checkout API

vscode:
  extensions:
    - ms-python.python
    - ms-python.vscode-pylance
